address        = "http://localhost:5000/terraform_state/my_state"
lock_address   = "http://localhost:5000/terraform_lock/my_state"
lock_method    = "PUT"
unlock_address = "http://localhost:5000/terraform_lock/my_state"
unlock_method  = "DELETE"